cycle
ivanskypro/lesson5 pull request #1
Opened 2021-10-17 09:33 UTC by ivanskypro

Добрый день!
Решил, помимо обычной домашки, немного уделить времени одному заданию из категории сложных 
По обычным заданиям вопросов нет, а вот по сложному есть.

Задача 4.
Я так и не понял, почему мне пришлось делать цикл до 29 (while (d <= 29) , потому что если я делал цикл до 30 while (d <= 30) , то в консоль мне выводились числа до 31, а не до 30 (т.е. нарушались условия задачи). Скорее всего я где-то ошибся, но вот где, непонятно.

2021-10-18 21:00 UTC, DisterDE requested changes
Нужно доработать задания по комментариям.

2021-10-18 21:00 UTC, DisterDE commented on src/pro/sky/lesson5/Main.java
> +                System.out.println("Сегодня пятница " + friday + ". Необходимо подготовить отчёт!");
Забыл скобки.

2021-10-18 21:00 UTC, DisterDE commented on src/pro/sky/lesson5/Main.java
> +            if (friday % 7 == 1)
Зачем эта проверка?
У нас есть дата первой пятницы.
Чтобы вывести все пятницы, нужно просто плюсовать к ней 7.

2021-10-18 21:00 UTC, DisterDE commented on src/pro/sky/lesson5/Main.java
> +                System.out.println(p);
Забыл скобки.

2021-10-18 21:00 UTC, DisterDE commented on src/pro/sky/lesson5/Main.java
> +        for (p = 1821; p <= 2121; p++) {
Откуда взялось числа 1821 и 2121?
Кажется, что они не подсчитаны компьютером, а взяты из головы.

2021-10-18 21:00 UTC, DisterDE commented on src/pro/sky/lesson5/Main.java
> +            d++;
Эти 3 строки говорят, что нужно было вводить цикл for, а не while.

2021-10-18 21:00 UTC, DisterRU commented on src/pro/sky/lesson5/Main.java
> +            d++;
Срабатывает на число + 1 от значения из скобок потому, что d проходит проверку, а потом тут же увеличивается на 1.
Следовательно, дальше в цикле уже число 30.
Нужно заменить <= на < и можно ставить 31.

2021-10-19 06:34 UTC, ivanskypro commented on src/pro/sky/lesson5/Main.java
> +            if (friday % 7 == 1)
К чему приплюсовать 7? Вообще не понял. Как это должно выглядеть?
Если я пишу:  "for (friday = 1; friday <= 31; friday = friday + 7)", цикл повторяется бесконечное количество раз и в консоли пишется бесконечно про пятницу 7! Напиши, пожалуйста, как это должно выглядеть, чтобы я понял в чём ошибка.

2021-10-19 07:17 UTC, closed without merging